### ISSUE TITLE
Crashes on every link add if not using vpn.

### ISSUE THREAD

**Issue by Bitwolfies** [manuGMG/1fichier-dl#8]
Dunno what more I can say, adding any link crashes the app, rendering it unusable. No 1fichier is not blocked on my network.

Windows 10 64bit. 2004 update.

**Comment by Darkwolf1515** [comment]
I think the bypassing might have been patched

**Comment by manuGMG** [comment]
I've just finished a download which means the bypassing part is completely functional at the moment.

Are you running the app directly from source or are you using the ZIP release?

**Comment by manuGMG** [comment]
In case you're **not** running from source, download the debug release from [here](https://github.com/manuGMG/1fichier-dl/releases/download/v0.1.4/1fichier-dl-win32-v0.1.4-debug.zip) and run it from **cmd** so you can see the error logs.

In order to do that open cmd and write down the exe location like this:
```
D:\Personal\1fichier-dl\1fichier-dl.exe
```

Then, send the error log here so I can recognise what the problem is.

**Comment by itzyeb** [comment]
im having the same issue and heres the error log 
[error log.txt](https://github.com/manuGMG/1fichier-dl/files/6394012/error.log.txt)

**Comment by TechGuy41** [comment]
Hi I am having issues where the app crashes everytime i put a link. 

Attached is my error log for this. 
[error.txt.txt](https://github.com/manuGMG/1fichier-dl/files/6863918/error.txt.txt)

**Comment by DaZEROrk** [comment]
Same here
when the connection to VPN close or disconnect, the program crashes
Win7 Ultimate 64bit SP1
[error.txt](https://github.com/manuGMG/1fichier-dl/files/6874630/error.txt)

**Comment by manuGMG** [comment]
Thanks for the logs. Will look into it.
